apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-scanner.fullname" . }}
  labels:
    {{- include "ai-scanner.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ai-scanner.serverSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
